#ifndef ClunetCommmon_h
#define ClunetCommmon_h


/************PACKET****************/

#define CLUNET_PACKET_OFFSET_SRC 0
#define CLUNET_PACKET_OFFSET_DST 1
#define CLUNET_PACKET_OFFSET_COMMAND 2
#define CLUNET_PACKET_OFFSET_SIZE 3
#define CLUNET_PACKET_OFFSET_DATA 4

#define CLUNET_PACKET_DATA_SIZE 128


/************ADDRESSES****************/

#define CLUNET_ADDRESS_SUPRADIN 0x00
#define CLUNET_ADDRESS_BROADCAST 0xFF

#define CLUNET_MULTICAST_DEVICE(address) (address & 0x80)
#define CLUNET_MULTICAST_VIRTUAL_DEVICE(address) (address & 0xF0)


/************COMMANDS****************/

#define CLUNET_COMMAND_DISCOVERY 0x00
#define CLUNET_COMMAND_DISCOVERY_RESPONSE 0x01
#define CLUNET_COMMAND_BOOT_CONTROL 0x02
#define CLUNET_COMMAND_REBOOT 0x03
#define CLUNET_COMMAND_BOOT_COMPLETED 0x04
#define CLUNET_COMMAND_TIME 0x08
#define CLUNET_COMMAND_TIME_INFO 0x09
#define CLUNET_COMMAND_PING 0xFE
#define CLUNET_COMMAND_PING_REPLY 0xFF
#define CLUNET_COMMAND_CHANNEL 0x10
#define CLUNET_COMMAND_CHANNEL_INFO 0x11
#define CLUNET_COMMAND_VOLUME 0x15
#define CLUNET_COMMAND_VOLUME_INFO 0x16
#define CLUNET_COMMAND_MUTE 0x17
#define CLUNET_COMMAND_EQUALIZER 0x18
#define CLUNET_COMMAND_EQUALIZER_INFO 0x19
#define CLUNET_COMMAND_FM 0x1C
#define CLUNET_COMMAND_FM_INFO 0x1D
#define CLUNET_COMMAND_POWER 0x1E
#define CLUNET_COMMAND_POWER_INFO 0x1F
#define CLUNET_COMMAND_SWITCH 0x20
#define CLUNET_COMMAND_SWITCH_INFO 0x21
#define CLUNET_COMMAND_BUTTON 0x22
#define CLUNET_COMMAND_BUTTON_INFO 0x23
#define CLUNET_COMMAND_TEMPERATURE 0x25
#define CLUNET_COMMAND_TEMPERATURE_INFO 0x26
#define CLUNET_COMMAND_HUMIDITY 0x27
#define CLUNET_COMMAND_HUMIDITY_INFO 0x28
#define CLUNET_COMMAND_PRESSURE 0x29
#define CLUNET_COMMAND_PRESSURE_INFO 0x2A
#define CLUNET_COMMAND_METEO 0x2E
#define CLUNET_COMMAND_METEO_INFO 0x2F
#define CLUNET_COMMAND_ONEWIRE_SEARCH 0x30
#define CLUNET_COMMAND_ONEWIRE_INFO 0x31
#define CLUNET_COMMAND_VOLTAGE 0x32
#define CLUNET_COMMAND_VOLTAGE_INFO 0x33
#define CLUNET_COMMAND_MOTION 0x40
#define CLUNET_COMMAND_MOTION_INFO 0x41
#define CLUNET_COMMAND_LIGHT_LEVEL 0x45
#define CLUNET_COMMAND_LIGHT_LEVEL_INFO 0x46
#define CLUNET_COMMAND_FAN 0x50
#define CLUNET_COMMAND_FAN_INFO 0x51
#define CLUNET_COMMAND_CHARGE 0x52
#define CLUNET_COMMAND_CHARGE_INFO 0x53
#define CLUNET_COMMAND_DOOR 0x55
#define CLUNET_COMMAND_DOOR_INFO 0x56
#define CLUNET_COMMAND_DIMMER 0x57
#define CLUNET_COMMAND_DIMMER_INFO 0x58
#define CLUNET_COMMAND_HEATFLOOR 0x60
#define CLUNET_COMMAND_HEATFLOOR_INFO 0x61
#define CLUNET_COMMAND_SERVO 0x66
#define CLUNET_COMMAND_SERVO_INFO 0x67
#define CLUNET_COMMAND_DEVICE_STATE 0x70
#define CLUNET_COMMAND_DEVICE_STATE_INFO 0x71
#define CLUNET_COMMAND_RC_BUTTON_PRESSED 0x75
#define CLUNET_COMMAND_RC_BUTTON_SEND 0x76
#define CLUNET_COMMAND_ANDROID 0xA0
#define CLUNET_COMMAND_DEBUG 0x99
#define CLUNET_COMMAND_SET_TIMER 0x09
#define CLUNET_COMMAND_BEEP 0x90

#endif
